name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: aarch64-apple-darwin
          override: true

      - name: Build
        run: cargo build --release --target aarch64-apple-darwin

      - name: Prepare artifact
        run: |
          mkdir -p dist
          cp target/aarch64-apple-darwin/release/kozutsumi dist/
          cd dist
          tar -czf kozutsumi-aarch64-apple-darwin.tar.gz kozutsumi
          rm kozutsumi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kozutsumi-tarball
          path: dist/kozutsumi-aarch64-apple-darwin.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: kozutsumi-tarball
          path: ./dist

      - name: Create or update latest tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -f latest ${{ github.sha }}
          git push origin refs/tags/latest --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: "Latest Release"
          files: ./dist/kozutsumi-aarch64-apple-darwin.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
