name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag"
        required: true

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: aarch64-apple-darwin
          override: true

      - name: Install required dependencies
        run: rustup target add aarch64-apple-darwin

      - name: Build release
        run: cargo build --release --target aarch64-apple-darwin

      - name: Prepare release binary
        run: |
          mkdir -p bin
          cp target/aarch64-apple-darwin/release/kozutsumi bin/

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          artifacts: bin/kozutsumi
