name: Release via Nix

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Zig Compiler
        uses: mlugg/setup-zig@v2.0.5

      # - name: Setup Rust Toolchain for GitHub CI
      #   uses: actions-rust-lang/setup-rust-toolchain@v1.15.1

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}

  # build:
  #   runs-on: macos-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Install Nix
  #       uses: cachix/install-nix-action@v26
  #       with:
  #         nix_path: nixpkgs=channel:nixos-unstable

  #     - name: Build package
  #       run: |
  #         nix build .#kozutsumi
  #         mkdir -p dist
  #         cp result/bin/kozutsumi dist/
  #         cd dist
  #         tar -czf kozutsumi-aarch64-apple-darwin.tar.gz kozutsumi
  #         rm kozutsumi

  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: kozutsumi-tarball
  #         path: dist/kozutsumi-aarch64-apple-darwin.tar.gz

  # release:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Download artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: kozutsumi-tarball
  #         path: ./dist

  #     - name: Create or update latest tag
  #       run: |
  #         git config user.name github-actions
  #         git config user.email github-actions@github.com
  #         git tag -f latest ${{ github.sha }}
  #         git push origin refs/tags/latest --force
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Create Release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         tag_name: latest
  #         name: "Latest Release"
  #         files: ./dist/kozutsumi-aarch64-apple-darwin.tar.gz
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
